version: '3'
services:
  app:
    build: .
    container_name: "container1"
    ports:
      - "3000:3000"
    command: bin/rails s
    volumes:
      - .:/container1
    tty: true
    stdin_open: true
